# Generated by Django 4.1.1 on 2022-09-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('part-time', 'Part Time')], default='full-time', max_length=250)),
                ('employment_level', models.CharField(choices=[('entry-level', 'Entry level'), ('mid-level', 'Mid-level'), ('senior', 'Senior')], default='entry-level', max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('job_description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('website', models.URLField(blank=True, null=True)),
                ('years_of_experience', models.CharField(choices=[('0 - 1', '0 - 1'), ('1 - 2', '1 - 2'), ('3 - 4', '3 - 4'), ('5 - 6', '5 - 6'), ('7 and above', '7 and above')], default='0 - 1', max_length=50)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('job_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job_api.jobadvert')),
            ],
        ),
    ]
